name: Build and Publish Python SDK (TestPyPi)

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build
        working-directory: python-sdk
      
      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Patch version in setup.py
        run: |
          base_version=$(grep '^version' setup.py | sed -E 's/version *= *"([^"]+)"/\1/')
          new_version="${base_version}+${{ steps.vars.outputs.sha_short }}"
          sed -i -E "s/^version *= *\"[^\"]+\"/version = \"${new_version}\"/" setup.py
        working-directory: python-sdk

      - name: Build package
        run: python -m build
        working-directory: python-sdk

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: python-sdk/dist/
