name: Build and Publish Python SDK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build
        working-directory: python-sdk

      - name: Copy README.md into SDK dir
        run: cp README.md python-sdk/

      - name: Build package
        run: python -m build
        working-directory: python-sdk

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://pypi.org/
          packages-dir: python-sdk/dist/
          verbose: true

